env:
  - RAILS_ENV=test
before_install: gem install bundler -v 1.10.6
language: ruby
rvm:
  - 2.2.3
  - 2.2.2
  - 2.1.7
  - 2.1.6
  - 2.0.0
  - ruby-1.9.3-p551
before_script:
  - bin/dummy_rake db:create db:migrate
