# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ab5aaf88f2a9fd40201f59d75a7b79632607118685021ea7f46404af9d809a595a1492da944053928ad64c35d8d2600e278372f487fb332ead3e37a1eed53bb

test:
  secret_key_base: ce61c0755d19363b7c1145a89e5d0b74d1e035ba5069df28c813cdbea7a327110ed788e645edb4b741c802a4d3a057fe541ed59e03dd9447c281ea0d3ad9c979

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
